### ISSUE TITLE
Organization cannot be null or empty

### ISSUE THREAD

**Issue by ryanlraines** [jamesnovak/PortalRecordsMoverConsole#5]
Getting this result when attempting to export only. 

```
Unhandled Exception: System.ArgumentNullException: Organization cannot be null or empty.
Parameter name: Organization Name
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmConnectionString)
   at PortalRecordsMover.AppCode.Exporter..ctor(ExportSettings settings) in *\Exporter.cs:line 26
   at PortalRecordsMover.PortalMover.Main(String[] args) in *\Program.cs:line 29
```

here is scrubbed settings file:

```
{
  "ActiveItemsOnly": false,
  /*"CreateFilter": "2017-11-24T12:00:00",
  "ModifyFilter": "2017-11-24T12:00:00",*/

  "PriorDaysToRetrieve": "100",

  /* Enum values, either number or name will work: CreateOnly=1, ModifyOnly, CreateAndModify
  */
  "DateFilterOptions": "CreateAndModify",
  "WebsiteFilter": "00000000-0000-0000-0000-000000000000",

  /*
    you can specify a date format mask here and the current date time will be added. 
      Use same value to export from the Source environment and immediately import into the Target
  */
  "ExportFilename": "portal export {0:yyyy-MM-dd}.xml",
  /*"ImportFilename": "portal export {0:yyyy-MM-dd}.xml",*/

  "SourceEnvironment": "fake.crm.dynamics.com",
  /*"TargetEnvironment": "test",*/
  "Username": "first.last@fake.onmicrosoft.com",
  "Password": "fake!234",

  "BatchCount": "10",
  "WebsiteIdMapping": [
    {
      "SourceId": "00000000-0000-0000-0000-000000000000",
      "TargetId": "00000000-0000-0000-0000-000000000000"
    }
  ],
  "SelectedEntities": [
    "adx_ad",
    "adx_adplacement",
    "adx_alertsubscription",
    "adx_bingmaplookup",
    "adx_casedeflection",
    "adx_bpf_c2857b638fa7473d8e2f112c232cebd8",
    "adx_contentaccesslevel",
    "adx_contentsnippet",
    "adx_entityform",
    "adx_entityformmetadata",
    "adx_entitylist",
    "adx_entitypermission",
    "adx_externalidentity",
    "adx_communityforum",
    "adx_communityforumaccesspermission",
    "adx_communityforumalert",
    "adx_communityforumannouncement",
    "adx_forumnotification",
    "adx_communityforumpost",
    "adx_communityforumthread",
    "adx_forumthreadtype",
    "adx_invitation",
    "adx_inviteredemption",
    "adx_pagealert",
    "adx_pagenotification",
    "adx_pagetag",
    "adx_pagetemplate",
    "adx_poll",
    "adx_polloption",
    "adx_pollplacement",
    "adx_pollsubmission",
    "adx_portalcomment",
    "adx_portallanguage",
    "adx_publishingstate",
    "adx_publishingstatetransitionrule",
    "adx_redirect",
    "adx_setting",
    "adx_shortcut",
    "adx_sitemarker",
    "adx_sitesetting",
    "adx_tag",
    "adx_urlhistory",
    "adx_webfile",
    "adx_webfilelog",
    "adx_webform",
    "adx_webformmetadata",
    "adx_webformsession",
    "adx_webformstep",
    "adx_weblink",
    "adx_weblinkset",
    "adx_webnotificationentity",
    "adx_webnotificationurl",
    "adx_webpage",
    "adx_webpageaccesscontrolrule",
    "adx_webpagehistory",
    "adx_webpagelog",
    "adx_webrole",
    "adx_webtemplate",
    "adx_website",
    "adx_websiteaccess",
    "adx_websitebinding",
    "adx_websitelanguage"
  ]

}

```

**Comment by jamesnovak** [comment]
This should be fixed with the latest release.  Apologies for the delay!
